### ISSUE TITLE
sqfc script not found issue

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [dedmen/ArmaScriptCompiler#21]
When i define functions in CfgFunction and place *.sqfc file in the mission (instead *.sqf) then arma generate error: "File not found". Game search "*.sqf" files. I must to place empty *.sqf file with same names to avoid this error.

class myFSMFunction
{
     ext = ".sqfc";
}
does not solving issue.

**Comment by dedmen** [comment]
The filename is just the sqf file. The extension is not .sqfc
You tell the game to load the sqf, and the game will then take care of checking if a sqfc file exists.

Also I think it won't work for FSM, Just normal scripts.
