### ISSUE TITLE
Detect #if __has_include

### ISSUE THREAD

**Issue by dedmen** [dedmen/ArmaScriptCompiler#6]
__has_include in SQF scripts cannot be reliably resolved at offline compile. These files should not be compiled

**Comment by killerswin2** [comment]
I'm currently adding ASC to antistasi and #if propressors is also failing for #if __A3_DEBUG__.
[scriptCompiler.txt](https://github.com/dedmen/ArmaScriptCompiler/files/10339125/scriptCompiler.txt)
A potential work around would be to allow for ASC to have a -D to define runtime macros.

**Comment by dedmen** [comment]
this was written when has_include was the only one.
https://community.bistudio.com/wiki/PreProcessor_Commands#has_include all of the runtime ones should block it.

But for now can always use
`#pragma ASC_ignoreFile` to ignore any file.
